//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixeval.Extensions.Translators.Ollama.Strings {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pixeval.Extensions.Translators.Ollama.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 通过Ollama调用本地运行的大模型翻译服务，需要预先安装 Ollama 的本地化字符串。
        /// </summary>
        internal static string ExtensionHostDescription {
            get {
                return ResourceManager.GetString("ExtensionHostDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama 翻译 的本地化字符串。
        /// </summary>
        internal static string ExtensionHostName {
            get {
                return ResourceManager.GetString("ExtensionHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通过 Ollama 调用的模型名称 的本地化字符串。
        /// </summary>
        internal static string ModelNameSettingsDescription {
            get {
                return ResourceManager.GetString("ModelNameSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama 模型名称 的本地化字符串。
        /// </summary>
        internal static string ModelNameSettingsLabel {
            get {
                return ResourceManager.GetString("ModelNameSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama 翻译 的本地化字符串。
        /// </summary>
        internal static string OllamaTranslatorLabel {
            get {
                return ResourceManager.GetString("OllamaTranslatorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ollama 本地服务器使用的端口号 的本地化字符串。
        /// </summary>
        internal static string PortSettingsDescription {
            get {
                return ResourceManager.GetString("PortSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号 的本地化字符串。
        /// </summary>
        internal static string PortSettingsLabel {
            get {
                return ResourceManager.GetString("PortSettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您翻译用户提供的文本到中文。除了翻译文本本身，不要回复任何无关的内容。 的本地化字符串。
        /// </summary>
        internal static string SystemInstructionSettingsDefaultValue {
            get {
                return ResourceManager.GetString("SystemInstructionSettingsDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引导模型对话的内容 的本地化字符串。
        /// </summary>
        internal static string SystemInstructionSettingsDescription {
            get {
                return ResourceManager.GetString("SystemInstructionSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统指令 的本地化字符串。
        /// </summary>
        internal static string SystemInstructionSettingsLabel {
            get {
                return ResourceManager.GetString("SystemInstructionSettingsLabel", resourceCulture);
            }
        }
    }
}
